### ISSUE TITLE
Game Crashes on Startup with various issues - suggestion to create readme

### ISSUE THREAD

**Issue by werzum** [TeamHypersomnia/Hypersomnia#267]
Hey,

I am a Pop OS user and had various problems trying to get the game to run on Pop OS (22.10).
Maybe a short readme for the installation would be helpful, despite the argument that Linux users should be tech-savy enough to find out on their own).
I had the issue that I `chown +X`ed only the Hypersomnia executable, which lead to various errors (either the application to not be able to establish an audio context or crashing with an unspecified error with an unspecified iostream_category_error).

I finally figured out I had to 
`sudo chown -R user:user hypersomnia/`
to own the entire folder, and then start the executable without sudo. This will probably seem trivial to some, but I still think that could be mentioned somewhere.

Hope this helps and of course thanks for your effort to create such a cool game!

**Comment by geneotech** [comment]
In case you're trying to build it yourself - I just found out there's a little problem with the ``run`` target - it's supposed to set the working directory automatically, I'm going to take a look.

**Comment by geneotech** [comment]
Yep, I found the issue, the ``run`` target didn't correctly set the current working directory (id did but the executable was overwriting it - it's meant to do it only for production so that the end-user could launch the binary from any working directory), the One-shot launch script in README should now work flawlessly.

**Comment by werzum** [comment]
hey, thanks for the quick reply - I actually wasnt trying to build it, just run the regular build. Maybe its PopOS specific? But glad it helped you fix another bug :+1:  Ill close this issue
