### ISSUE TITLE
Error while loading shared libraries: libunwind.so.1

### ISSUE THREAD

**Issue by David-Valters** [TeamHypersomnia/Hypersomnia#271]
./Hypersomnia: error while loading shared libraries: libunwind.so.1: cannot open shared object file: No such file or directory

but libunwind-1.6.2-2 is already installed

OS: Arch Linux

### release_notes.txt:
> 1.2.8309
> fee76723859175292afc70872cdbd0fbfc36c7b1
> Fix build error

**Comment by geneotech** [comment]
This is a known error - for now you have to symlink the libunwind library on your system to point to ``libunwind.so.1``, e.g. ``sudo ln -s /usr/lib/libunwind.so.8 /usr/lib/libunwind.so.1``

**Comment by David-Valters** [comment]
> This is a known error - for now you have to symlink the libunwind library on your system to point to `libunwind.so.1`, e.g. `sudo ln -s /usr/lib/libunwind.so.8 /usr/lib/libunwind.so.1`

why does such a problem exist at all, and what is the difficulty of solving it?
(interested as a developer)

**Comment by geneotech** [comment]
As you have noticed, Arch Linux ships its ``libunwind`` library under a different name and the executable cannot find it.
The executable is built on an Ubuntu server and thus launches flawlessly on Ubuntu distros.
We're working on a workflow that'll produce AppImage executables able to run on all distros out-of-the-box - see:   https://github.com/TeamHypersomnia/Hypersomnia/pull/270

As for the dependency, it looks like LLVM's libc++ is using it to unwind the stack when handling exceptions. I've been trying to remove that dependency (even today actually) but have been unsuccessful so far. Surprisingly, building the same application on Arch Linux does not produce that libunwind.so.1 dependency, whereas building on Ubuntu does.

**Comment by geneotech** [comment]
Hey there! We're now shipping the game in the portable ``AppImage`` format.
This should solve all problems you have experienced with the missing libraries:

https://hypersomnia.xyz/builds/latest/Hypersomnia.AppImage
