### ISSUE TITLE
ibssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SpiritOTHawk** [TeamHypersomnia/Hypersomnia#274]
./Hypersomnia: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by geneotech** [comment]
Hey there! Are you sure you're launching the ``.AppImage`` build? This comes with all needed libraries and should launch flawlessly. The download link in ``README.md`` points to the AppImage as well.

The ``.tar.gz`` distribution is meant only for developers. If you had it previously, I recommend switching to ``AppImage`` and just copying your user folder to ``.config/Hypersomnia/user``.

**Comment by SpiritOTHawk** [comment]
> Hey there! Are you sure you're launching the `.AppImage` build? This comes with all needed libraries and should launch flawlessly. The download link in `README.md` points to the AppImage as well.
> 
> The `.tar.gz` distribution is meant only for developers. If you had it previously, I recommend switching to `AppImage` and just copying your user folder to `.config/Hypersomnia/user`.

Okay, thanks

**Comment by geneotech** [comment]
Oh, indeed the link was out of date on ``hypersomnia.xyz``, I updated that one also. Thanks for pointing it out!
