### ISSUE TITLE
Is there a randomization of maps and modes on a dedicated server

### ISSUE THREAD

**Issue by Timofei302** [TeamHypersomnia/Hypersomnia#275]
I'm going to run my dedicated server, and I'd like to have the modes and maps change independently at the end of the matches.

**Comment by Lopix77** [comment]
not just yet, but it is in the pipeline

**Comment by geneotech** [comment]
Hey there, I have good news! I've implemented map cycling through the following vars in config.lua:

```lua
    cycle = "REPEAT_CURRENT", -- | "LIST" | "ALL_ON_DISK"

    -- Just add "arena mode" or "arena" for the map-default mode.
    -- "mode" can be bomb_defusal, gun_game or quick_test.
    cycle_list = {
      "de_cyberaqua",
      "fy_minilab bomb_defusal",
      "de_silo"
    }, 

    -- Convenience var to override the game mode
    -- for all maps on the list or on the disk.
    cycle_always_game_mode = "",

    -- Applies when cycle is "LIST" or "ALL_ON_DISK".
    cycle_randomize_order = false,
```

You can also comfortably manage these from UI in RCON menu (under F8):

![image](https://github.com/TeamHypersomnia/Hypersomnia/assets/3588717/38716b92-0d70-46a7-b841-3fb101812c8d)

Hope you enjoy it! :smiley: 

One more thing you'll like - I've now also implemented a ``--daily-autoupdate`` flag. From https://hypersomnia.xyz/servers:

> "--daily-autoupdate" flag causes the server to update itself every 24 hours at 03:00 AM (your local time), if newer game version is available. This flag is highly recommended so you don't have to keep up with frequent game updates (the game is in active development). You can also set the flag in RCON settings (press F8 and go to Vars tab).

Thank you for hosting a server in your area :heart:

**Comment by Timofei302** [comment]
> Hey there, I have good news! I've implemented map cycling through the following vars in config.lua (see default_config.lua for reference):
> 
> ```lua
>     cycle = "REPEAT_CURRENT", -- | "LIST" | "ALL_ON_DISK"
> 
>     -- Just add "arena mode" or "arena" for the map-default mode.
>     -- "mode" can be bomb_defusal, gun_game or quick_test.
>     cycle_list = {
>       "de_cyberaqua",
>       "fy_minilab bomb_defusal",
>       "de_silo"
>     }, 
> 
>     -- Convenience var to override the game mode
>     -- for all maps on the list or on the disk.
>     cycle_always_game_mode = "",
> 
>     -- Applies when cycle is "LIST" or "ALL_ON_DISK".
>     cycle_randomize_order = false,
> ```
> 
> You can also comfortably manage these from UI in RCON menu (under F8):
> 
> ![image](https://user-images.githubusercontent.com/3588717/275307334-38716b92-0d70-46a7-b841-3fb101812c8d.png) Anything you set will be remembered across launches, the RCON settings are written out to `config.lua` whenever you apply them.
> 
> Hope you enjoy it! 😃
> 
> One more thing you'll like - I've now also implemented a `--daily-autoupdate` flag. From https://hypersomnia.xyz/servers:
> 
> > "--daily-autoupdate" flag causes the server to update itself every 24 hours at 03:00 AM (your local time), if newer game version is available. This flag is highly recommended so you don't have to keep up with frequent game updates (the game is in active development). You can also set the flag in RCON settings (press F8 and go to Vars tab).
> 
> Thank you for hosting a community server ❤️

Cool! I will need to update the server configurations and Systemd service when I have free time))
