### ISSUE TITLE
Add graphical title into the press kit

### ISSUE THREAD

**Issue by vintprox** [TeamHypersomnia/Hypersomnia#277]
There is a text on all your promoart that says "Hypersomnia". But it never comes in isolation, or at least I cannot find it easily. Will this not be appropriate to add this graphical element into the [press kit](https://hypersomnia.xyz/press)?

**Comment by geneotech** [comment]
Great idea! I just added it - refresh with ctrl+f5 :)

**Comment by vintprox** [comment]
Ah, you've beat me to it! I was about to finish cropping it myself. XDDDDD

Good speed!

**Comment by vintprox** [comment]
Here's a neat poster for all your Kbin posting ;)

![hypersomnia-3x2-poster](https://github.com/TeamHypersomnia/Hypersomnia/assets/5708819/8601459a-8450-4d5a-8c57-80fb54345410)

[Check out my post](https://kbin.melroy.org/m/drbboard/t/45549/Hypersomnia-FLOSS-Multiplayer-Top-Down-Shooter)
