### ISSUE TITLE
Server names are missing

### ISSUE THREAD

**Issue by Timofei302** [TeamHypersomnia/Hypersomnia#278]
Out of the blue, the names of all unofficial servers in the client disappeared.
![Screenshot_20231017_185722](https://github.com/TeamHypersomnia/Hypersomnia/assets/59145732/036b478e-f502-4f4f-8867-c293252a1c07)
Updating the server list does not help.

**Comment by geneotech** [comment]
Hey, it appears you have "Streamer mode" ticked in Settings (at the very top in General). DIsable it and you should be good to go :smile:

**Comment by geneotech** [comment]
Oh, you might have accidentally enabled it by pressing F9. Indeed, I should probably notify the user or change the binding

**Comment by Timofei302** [comment]
> Oh, you might have accidentally enabled it by pressing F9. Indeed, I should probably notify the user that it happened or change the binding

Oh yeah. I was setting up my server now, and I first clicked the wrong button when I logged into RCON 😅
