### ISSUE TITLE
Explanation of the network synchronization

### ISSUE THREAD

**Issue by JadeVand** [TeamHypersomnia/Hypersomnia#284]
Thank you for this, it’s such a huge resource for the gamedev community! 

According to your README, the players merely send inputs and then replication or local simulation is done by each individual player. This is similar to how fighting games work. Are you performing roll-back and clock synchronization as well as fixed frame updates to ensure synchronized tick rates? I love C but I have difficult time understanding C++ :(

**Comment by geneotech** [comment]
Hello! From what I know, fighting games are p2p which is where the whole complexity comes from, whereas Hypersomnia is a completely client-server architecture. I've been asked the same question about a fighting game enthusiast and they made me realize I'm doing [something called GGPO:](https://en.wikipedia.org/wiki/GGPO#Design)


> GGPO uses a [netcode](https://en.wikipedia.org/wiki/Netcode) technique called "[rollback](https://en.wikipedia.org/wiki/Rollback_netcode)". Rather than waiting for input to be received from other players before simulating the next frame, GGPO predicts the inputs they will send and simulates the next frame without delay using that assumption. When other players’ inputs arrive, if any input didn't match the prediction, GGPO rolls back the state of the game to the last correct state, then replays all players’ revised inputs back until the current frame. The hope is that the predictions will be correct most of the time, allowing smooth play with minimal sudden changes to the game state.

This is exactly how it works in Hypersomnia but it is the server that governs what inputs were applied to every simulation step, not the clients.

I don't synchronize clocks at all - it is an auto-correcting system. I don't even use timestamps for messages. There is simply a bidirectional stream of completely reliable messages over UDP, the client sends its inputs every step @ 60Hz (even if there were none, it just says "empty input"). The client begins simluating its own world forward the moment it connects, and populates the "predicted inputs (steps)" vector until the server updates start to arrive. Server, within every step update packet (@ 60Hz too) says **how many steps worth of client inputs have been accepted**. The client pops that many steps from the front of the vector of predicted inputs, then re-creates the "predicted" (rendered) game world by re-applying the remaining predicted inputs on the "referential" (off-screen) server world (which contains the streamed, always correct server state, and is only ever simulated forward).

Thus the amount of "prediction" is always proportional to the apparent network lag, and is 100% adaptive to fluctuations in latency.

**Comment by geneotech** [comment]
Hello! From what I know, fighting games are p2p which is where the whole complexity comes from, whereas Hypersomnia is a completely client-server architecture. I've been asked the same question by a fighting game enthusiast and they made me realize I'm doing [something called GGPO:](https://en.wikipedia.org/wiki/GGPO#Design)


> GGPO uses a [netcode](https://en.wikipedia.org/wiki/Netcode) technique called "[rollback](https://en.wikipedia.org/wiki/Rollback_netcode)". Rather than waiting for input to be received from other players before simulating the next frame, GGPO predicts the inputs they will send and simulates the next frame without delay using that assumption. When other players’ inputs arrive, if any input didn't match the prediction, GGPO rolls back the state of the game to the last correct state, then replays all players’ revised inputs back until the current frame. The hope is that the predictions will be correct most of the time, allowing smooth play with minimal sudden changes to the game state.

This is exactly how it works in Hypersomnia but it is the server that governs what inputs were applied to every simulation step, not the clients.

I don't synchronize clocks at all - it is an auto-correcting system. I don't even use timestamps for messages. There is simply a bidirectional stream of completely reliable messages over UDP, the client sends its inputs every step @ 60Hz (even if there were none, it just says "empty input"). The client begins simluating its own world forward the moment it connects, and populates the "predicted inputs (steps)" vector until the server updates start to arrive. Server, within every step update packet (@ 60Hz too) says **how many steps worth of client inputs have been accepted**. The client pops that many steps from the front of the vector of predicted inputs, then re-creates the "predicted" (rendered) game world by re-applying the remaining predicted inputs on the "referential" (off-screen) server world (which contains the streamed, always correct server state, and is only ever simulated forward).

Thus the amount of "prediction" is always proportional to the apparent network lag, and is 100% adaptive to fluctuations in latency.

**Comment by JadeVand** [comment]
Hi! Thank you! 
So from what I understand, the client sends inputs at a fixed rate to the server. The server will simulate the game forward on the assumption that the client's input did not change from their previous sent input. When a change does occur, the server will undo the game state and apply the correct input for that target frame then resimulate forward again to the current state. And at a fixed rate it will send that clients predicted input or corrected input, along with position, velocity and rotation?

**Comment by geneotech** [comment]
> the client sends inputs at a fixed rate to the server.

Yes.

> The server will simulate the game forward on the assumption that the client's input did not change from their previous sent input.

Yes, the server does too, although my explanation focused on the client-side, and yes, clients do make this assumption as well.

>  When a change does occur, the server will undo the game state and apply the correct input for that target frame then resimulate forward again to the current state. 

No, it is the clients who do it. The server never rolls back any state, it mercilessly marches forward in time and accepts clients' inputs as they are received, immediately to the soonest simulation step.

> And at a fixed rate it will send that clients predicted input or corrected input, along with position, velocity and rotation?

No, the server does not send any predicted input. It also does not send any position, velocity or rotation data except when connection is initialized (clients need starting data to deterministically simulate from). Later it just broadcasts the "canonical" inputs of all players it decided to apply to every simulation step.

**Comment by JadeVand** [comment]
I think I understand now! The server behaves much like lock-step where it waits for all clients inputs to arrive, simulates the game forward then it relays the clients inputs back to the clients. Where the clients can then perform rollback and correct their own simulation of the game?

**Comment by geneotech** [comment]
Also, like I mentioned wrt. clock synchronization: with each canonical step relayed from server to the client, the server includes the number of client "input steps" that have been accepted - so it could be "5" after the merge of jitter buffer, always "1" under normal conditions, and "0" for the duration of a lag spike. This is how the system self-corrects for lag fluctuations.
